#!/bin/bash

if [[ $1 == "compile" ]]; then
  java -jar $PIZZA_HOME/libs/Pizza-0.4.jar compile $2
fi
if [[ $1 == "--version" ]]; then
  java -jar $PIZZA_HOME/libs/Pizza-0.4.jar --version
fi
if [[ $1 == "--help" ]]; then
  java -jar $PIZZA_HOME/libs/Pizza-0.4.jar --help
fi