#!/bin/bash

if [[ $1 == "compile" ]]; then
  java -jar $PIZZA_HOME/build/libs/Pizza-0.3.jar compile $2
fi
if [[ $1 == "--version" ]]; then
  java -jar $PIZZA_HOME/build/libs/Pizza-0.3.jar --version
fi
if [[ $1 == "--help" ]]; then
  java -jar $PIZZA_HOME/build/libs/Pizza-0.3.jar --help
fi