#!/bin/bash

if [[ $1 == "compile" ]]; then
  java -jar $PIZZA_HOME/build/libs/Pizza-0.2\ Beta.jar compile $2
  rm -rf $TMPDIR/pizza
fi
if [[ $1 == "--version" ]]; then
  java -jar $PIZZA_HOME/build/libs/Pizza-0.2\ Beta.jar --version
fi